# **Economics of Emissions** 
### Prediction Analysis of the Contribution of Emissions to the GDP of the states in the United States of America using a Cluster-Spatio-Temporal Approach

## - Emissions Data from EDGAR
### Data Importation

In [1]:
import pandas as pd

# Initializing the file path
file_path = "EDGAR_2024_GHGs_CO2eq_AR5_NUTS2_by_country_sector_1990-2023_v3.xlsx"

# List of Sheets to import
sheets_to_load = ["Fossil CO2", "CH4 AR5", "N2O AR5", "F-gases AR5"]

# Skipping the first 6 rows since column names start in row 7
dfs = pd.read_excel(
    file_path,
    sheet_name=sheets_to_load,
    skiprows=6  
)

# Getting the data on emissions 
df_Fossil_CO2 = dfs["Fossil CO2"]
df_CH4_AR5 = dfs["CH4 AR5"]
df_N2O_AR5 = dfs["N2O AR5"]
df_F_gases_AR5 = dfs["F-gases AR5"]

### Data Overview

In [2]:
print(df_Fossil_CO2.head())

  Substance  ISO Country Subnational code * Subnational desc     Sector  \
0       CO2  ABW   Aruba                NaN              NaN  Buildings
1       CO2  ABW   Aruba                NaN              NaN    Dom_Avi
2       CO2  ABW   Aruba                NaN              NaN   Dom_Ship
3       CO2  ABW   Aruba                NaN              NaN     Energy
4       CO2  ABW   Aruba                NaN              NaN   Industry

       Y_1990      Y_1991      Y_1992      Y_1993  ...      Y_2014  \
0   20.195578   26.065616   25.015368   23.974950  ...   33.925451
1    6.792256    8.148331    8.035436    7.282572  ...   18.429354
2    2.079712    2.371701    1.898307    2.719606  ...    9.191439
3  109.100181  118.315792  135.819239  136.076375  ...  222.238026
4   10.287837   10.779957    9.802945    9.148197  ...   24.342087

       Y_2015      Y_2016      Y_2017      Y_2018      Y_2019      Y_2020  \
0   36.351845   45.249942   38.721076   42.424381   51.835970   38.022131
1   18.900723   18.986393   19.690313   16.584860   25.492941   11.216762
2    9.637073   10.209681    9.763253    9.615795   11.382993    9.866186
3  230.102165  240.807934  223.432549  226.341226  268.030985  232.923266
4   26.405802   23.980960   35.443537   30.330976   31.678723   27.889582

       Y_2021      Y_2022      Y_2023
0   41.407337   41.123888   43.125141
1   12.473237   17.615120   20.659366
2   10.696811   10.876347   12.160220
3  253.010310  251.278359  263.506570
4   35.623896   35.385055   37.035201

[5 rows x 40 columns]

In [3]:
print(df_CH4_AR5.head())

         Substance  ISO Country Subnational code * Subnational desc  \
0  GWP_100_AR5_CH4  ABW   Aruba                NaN              NaN
1  GWP_100_AR5_CH4  ABW   Aruba                NaN              NaN
2  GWP_100_AR5_CH4  ABW   Aruba                NaN              NaN
3  GWP_100_AR5_CH4  ABW   Aruba                NaN              NaN
4  GWP_100_AR5_CH4  ABW   Aruba                NaN              NaN

        Sector    Y_1990    Y_1991    Y_1992    Y_1993  ...    Y_2014  \
0  Agriculture  1.435864  1.435864  1.435864  1.435864  ...  1.435864
1    Buildings  0.204031  0.220605  0.213402  0.205528  ...  0.513036
2      Dom_Avi  0.001332  0.001599  0.001576  0.001428  ...  0.003610
3     Dom_Ship  0.005515  0.006289  0.005030  0.007216  ...  0.024383
4       Energy  0.081684  0.094357  0.108332  0.109035  ...  0.226036

     Y_2015    Y_2016    Y_2017    Y_2018    Y_2019    Y_2020    Y_2021  \
0  1.435864  1.435864  1.435864  1.435864  1.441069  1.446300  1.453937
1  0.491390  0.579916  0.542264  0.551108  0.459838  0.550313  0.535538
2  0.003703  0.003720  0.003858  0.003250  0.004994  0.002198  0.002445
3  0.025588  0.027107  0.025904  0.025513  0.030131  0.026105  0.028303
4  0.235647  0.242824  0.229015  0.236398  0.282106  0.249545  0.269588

     Y_2022    Y_2023
0  1.457551  1.461174
1  0.420748  0.426208
2  0.003453  0.004050
3  0.028778  0.032175
4  0.280608  0.292819

[5 rows x 40 columns]

In [4]:
print(df_N2O_AR5.head())

         Substance  ISO Country Subnational code * Subnational desc  \
0  GWP_100_AR5_N2O  ABW   Aruba                NaN              NaN
1  GWP_100_AR5_N2O  ABW   Aruba                NaN              NaN
2  GWP_100_AR5_N2O  ABW   Aruba                NaN              NaN
3  GWP_100_AR5_N2O  ABW   Aruba                NaN              NaN
4  GWP_100_AR5_N2O  ABW   Aruba                NaN              NaN

        Sector    Y_1990    Y_1991    Y_1992    Y_1993  ...    Y_2014  \
0  Agriculture  0.941940  0.937759  0.937489  0.940018  ...  1.016501
1    Buildings  0.361852  0.415175  0.442342  0.436519  ...  0.144701
2      Dom_Avi  0.050413  0.060528  0.059647  0.054054  ...  0.136675
3     Dom_Ship  0.014912  0.017006  0.013603  0.019514  ...  0.065932
4       Energy  0.178176  0.200589  0.230358  0.231460  ...  0.440302

     Y_2015    Y_2016    Y_2017    Y_2018    Y_2019    Y_2020    Y_2021  \
0  1.016501  1.016501  1.016501  1.016501  1.020186  1.023889  1.029296
1  0.147003  0.165319  0.151554  0.239490  0.279776  0.230883  0.254064
2  0.140170  0.140831  0.146036  0.123054  0.189052  0.083211  0.092559
3  0.069192  0.073299  0.070046  0.068989  0.081476  0.070590  0.076533
4  0.457841  0.474385  0.444971  0.456214  0.543176  0.477663  0.516957

     Y_2022    Y_2023
0  1.031854  1.034420
1  0.245803  0.256300
2  0.130715  0.153305
3  0.077817  0.087003
4  0.529985  0.553954

[5 rows x 40 columns]

In [5]:
print(df_F_gases_AR5.head())

             Substance  ISO      Country Subnational code * Subnational desc  \
0  GWP_100_AR5_F-gases  AFG  Afghanistan                NaN              NaN
1  GWP_100_AR5_F-gases  AGO       Angola                NaN              NaN
2  GWP_100_AR5_F-gases  ALB      Albania               AL01             Veri
3  GWP_100_AR5_F-gases  ALB      Albania               AL02           Qender
4  GWP_100_AR5_F-gases  ALB      Albania               AL03              Jug

     Sector    Y_1990    Y_1991    Y_1992    Y_1993  ...      Y_2014  \
0  Industry  0.170367  1.109189  1.754508  2.831944  ...  358.812736
1  Industry  0.133035  0.775925  1.216209  1.940550  ...  252.031587
2  Industry  0.322466  0.508110  0.733048  1.191365  ...   33.497433
3  Industry  0.397343  0.626095  0.903263  1.556789  ...   45.178798
4  Industry  0.226455  0.356826  0.514790  0.844132  ...   20.676865

       Y_2015      Y_2016      Y_2017      Y_2018      Y_2019      Y_2020  \
0  396.512663  452.375560  507.475710  574.910306  634.376187  695.043063
1  277.645130  315.598689  353.034034  398.849473  439.250920  480.468331
2   36.708850   41.467454   46.161086   52.561419   57.690960   62.924099
3   49.510115   55.928159   62.258574   70.470781   77.348121   84.364358
4   22.659167   25.596497   28.493722   30.918798   33.936206   37.014554

       Y_2021      Y_2022      Y_2023
0  757.565514  818.450583  879.808715
1  522.946430  564.312082  605.999136
2   68.317301   73.569261   79.729531
3   91.595196   98.636668  105.891993
4   40.187058   43.276478   45.363257

[5 rows x 40 columns]

### Data Cleaning, Transformation and Feature Engineering

In [9]:
# Filtering each dataset for USA and Industry Sector
dfs1 = [df_Fossil_CO2, df_CH4_AR5, df_N2O_AR5, df_F_gases_AR5]
df_names = ["Fossil_CO2", "CH4_AR5", "N2O_AR5", "F_gases_AR5"]

# Initializing the filtered dataset
filtered_dfs = []

# Lopping over each dataset
for df, name in zip(dfs1, df_names):
    temp = df.copy()

    # Filtering for United States and Industry sector
    temp = temp[(temp["Country"] == "United States") & (temp["Sector"] == "Industry")]

    # Reshaping from wide to long 
    temp = temp.melt(
        id_vars=["Country", "Subnational desc"],
        value_vars=[col for col in temp.columns if col.startswith("Y_")],
        var_name="Year",
        value_name="Emission"
    )

    # Renaming columns
    temp["Year"] = temp["Year"].str.replace("Y_", "").astype(int)
    temp = temp.rename(columns={"Subnational desc": "State"})
    temp["Emission_Type"] = name

    # Reordering columns
    temp = temp[["Country", "State", "Year", "Emission_Type", "Emission"]]
    filtered_dfs.append(temp)

# Combining all datasets
df_combined = pd.concat(filtered_dfs, ignore_index=True)

# Aggregating by State and Year 
df_agg = (
    df_combined.groupby(["Country", "State", "Year"], as_index=False)
    .agg({"Emission": "sum"})
)

In [30]:
# Data Overview
df_combined.head()

         Country    State  Year Emission_Type      Emission
0  United States  Alabama  1990    Fossil_CO2  25871.992959
1  United States  Florida  1990    Fossil_CO2  24669.096219
2  United States  Georgia  1990    Fossil_CO2  32070.683542
3  United States   Hawaii  1990    Fossil_CO2   2731.980280
4  United States    Idaho  1990    Fossil_CO2   2634.310875

In [10]:
# Data Overview
df_agg.head()

         Country    State  Year      Emission
0  United States  Alabama  1990  42341.939842
1  United States  Alabama  1991  39217.818686
2  United States  Alabama  1992  36762.376140
3  United States  Alabama  1993  36945.520425
4  United States  Alabama  1994  37441.987568

In [11]:
# Checking data info
df_agg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1734 entries, 0 to 1733
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Country   1734 non-null   object
 1   State     1734 non-null   object
 2   Year      1734 non-null   int32
 3   Emission  1734 non-null   float64
dtypes: float64(1), int32(1), object(2)
memory usage: 47.5+ KB

In [13]:
#Checking missing data
df_agg.isnull().sum()

Country     0
State       0
Year        0
Emission    0
dtype: int64

## - GDP Data from FRED
### Data Importation

In [15]:
# Initializing the file path
file_path1 = "GDP_per_state_Q1_1990_to_Q2_2023.xlsx"

# List of Sheets to import
sheets_to_load1 = ["Quarterly"]

# Importing Data
dfs = pd.read_excel(
    file_path1,
    sheet_name=sheets_to_load1 
)

# Getting the data on emissions 
df_Quarterly = dfs["Quarterly"]

### Data Overview

In [17]:
print(df_Quarterly.head())

  observation_date  AKMANRQGSP_20230630  ALMANRQGSP_20230630  \
0       2005-01-01               1833.2              30929.2
1       2005-04-01               1664.4              30815.2
2       2005-07-01               1737.8              30786.0
3       2005-10-01               1738.3              32215.7
4       2006-01-01               1836.9              32799.7

   ARMANRQGSP_20230630  AZMANRQGSP_20230630  CAMANRQGSP_20230630  \
0              18889.2              18331.4             202390.2
1              19030.2              17943.1             209451.8
2              19391.3              18290.0             215378.7
3              20131.7              19061.2             219580.3
4              20615.1              19870.6             233808.4

   COMANRQGSP_20230630  CTMANRQGSP_20230630  DCMANRQGSP_20220930  \
0              16371.0              38278.4                363.0
1              16540.0              37349.9                356.3
2              17751.8              37001.3                332.8
3              17807.0              38217.8                327.1
4              18276.6              43768.1                312.4

   DEMANRQGSP_20230630  ...  SDMANRQGSP_20230630  TNMANRQGSP_20230630  \
0               4907.7  ...               3275.4              44064.0
1               5075.4  ...               3230.5              43939.3
2               5703.3  ...               3186.8              44592.1
3               6097.8  ...               3190.8              46016.5
4               5354.0  ...               3531.4              46353.7

   TXMANRQGSP_20230630  UTMANRQGSP_20230630  VAMANRQGSP_20230630  \
0             176640.0              11462.6              39150.7
1             174531.1              11798.4              39870.1
2             175842.4              12027.1              39771.3
3             178913.7              12469.7              40752.5
4             193993.4              13069.8              40814.8

   VTMANRQGSP_20230630  WAMANRQGSP_20230630  WIMANRQGSP_20230630  \
0               2675.8              42420.0              51044.0
1               2661.8              44912.9              51099.7
2               2676.3              45023.6              51807.7
3               2885.7              46631.5              52602.1
4               3073.8              47767.0              54617.8

   WVMANRQGSP_20230630  WYMANRQGSP_20230630
0               7552.1               2238.8
1               7528.6               2174.8
2               7562.5               2162.8
3               7721.6               2274.4
4               7728.1               2285.4

[5 rows x 52 columns]

### Data Cleaning, Transformation and Feature Engineering

In [18]:
#  Converting from wide format to long format
df_Quarterly_long = df_Quarterly.melt(
    id_vars=["observation_date"],
    var_name="State_Code",
    value_name="Manufacturing_GDP"
)

df_Quarterly_long.head()

  observation_date           State_Code  Manufacturing_GDP
0       2005-01-01  AKMANRQGSP_20230630             1833.2
1       2005-04-01  AKMANRQGSP_20230630             1664.4
2       2005-07-01  AKMANRQGSP_20230630             1737.8
3       2005-10-01  AKMANRQGSP_20230630             1738.3
4       2006-01-01  AKMANRQGSP_20230630             1836.9

In [19]:
# Extracting the 2-letter state abbreviation 
df_Quarterly_long["State"] = df_Quarterly_long["State_Code"].str[:2]
df_Quarterly_long.head()

  observation_date           State_Code  Manufacturing_GDP State
0       2005-01-01  AKMANRQGSP_20230630             1833.2    AK
1       2005-04-01  AKMANRQGSP_20230630             1664.4    AK
2       2005-07-01  AKMANRQGSP_20230630             1737.8    AK
3       2005-10-01  AKMANRQGSP_20230630             1738.3    AK
4       2006-01-01  AKMANRQGSP_20230630             1836.9    AK

In [20]:
# Mapping the state abbreviations for full state names
us_states = {
    'AK': 'Alaska', 'AL': 'Alabama', 'AR': 'Arkansas', 'AZ': 'Arizona', 'CA': 'California',
    'CO': 'Colorado', 'CT': 'Connecticut', 'DC': 'District of Columbia', 'DE': 'Delaware',
    'FL': 'Florida', 'GA': 'Georgia', 'HI': 'Hawaii', 'IA': 'Iowa', 'ID': 'Idaho',
    'IL': 'Illinois', 'IN': 'Indiana', 'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana',
    'MA': 'Massachusetts', 'MD': 'Maryland', 'ME': 'Maine', 'MI': 'Michigan', 'MN': 'Minnesota',
    'MO': 'Missouri', 'MS': 'Mississippi', 'MT': 'Montana', 'NC': 'North Carolina',
    'ND': 'North Dakota', 'NE': 'Nebraska', 'NH': 'New Hampshire', 'NJ': 'New Jersey',
    'NM': 'New Mexico', 'NV': 'Nevada', 'NY': 'New York', 'OH': 'Ohio', 'OK': 'Oklahoma',
    'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina',
    'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah', 'VA': 'Virginia',
    'VT': 'Vermont', 'WA': 'Washington', 'WI': 'Wisconsin', 'WV': 'West Virginia',
    'WY': 'Wyoming'
}

df_Quarterly_long["State_Name"] = df_Quarterly_long["State"].map(us_states)
df_Quarterly_long.head()

  observation_date           State_Code  Manufacturing_GDP State State_Name
0       2005-01-01  AKMANRQGSP_20230630             1833.2    AK     Alaska
1       2005-04-01  AKMANRQGSP_20230630             1664.4    AK     Alaska
2       2005-07-01  AKMANRQGSP_20230630             1737.8    AK     Alaska
3       2005-10-01  AKMANRQGSP_20230630             1738.3    AK     Alaska
4       2006-01-01  AKMANRQGSP_20230630             1836.9    AK     Alaska

In [21]:
# Cleanin up and reordering columns ---
df_Quarterly_long = df_Quarterly_long.rename(columns={"observation_date": "Date"})
df_Quarterly_long = df_Quarterly_long[["Date", "State_Name", "Manufacturing_GDP"]]
df_Quarterly_long.head()

        Date State_Name  Manufacturing_GDP
0 2005-01-01     Alaska             1833.2
1 2005-04-01     Alaska             1664.4
2 2005-07-01     Alaska             1737.8
3 2005-10-01     Alaska             1738.3
4 2006-01-01     Alaska             1836.9

In [22]:
# Convert Date to datetime 
df_Quarterly_long["Date"] = pd.to_datetime(df_Quarterly_long["Date"])
# Creating year variable
df_Quarterly_long["Year"] = df_Quarterly_long["Date"].dt.year
df_Quarterly_long.head()

        Date State_Name  Manufacturing_GDP  Year
0 2005-01-01     Alaska             1833.2  2005
1 2005-04-01     Alaska             1664.4  2005
2 2005-07-01     Alaska             1737.8  2005
3 2005-10-01     Alaska             1738.3  2005
4 2006-01-01     Alaska             1836.9  2006

In [24]:
# Aggregating over yearly data
df_yearly = df_Quarterly_long.groupby(["Year", "State_Name"], as_index=False)["Manufacturing_GDP"].sum()
df_yearly.head()

   Year  State_Name  Manufacturing_GDP
0  2005     Alabama           124746.1
1  2005      Alaska             6973.7
2  2005     Arizona            73625.7
3  2005    Arkansas            77442.4
4  2005  California           846801.0

In [25]:
# Checking data info
df_yearly.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 969 entries, 0 to 968
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               969 non-null    int64
 1   State_Name         969 non-null    object
 2   Manufacturing_GDP  969 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 22.8+ KB

In [26]:
#Checking missing data
df_yearly.isnull().sum()

Year                 0
State_Name           0
Manufacturing_GDP    0
dtype: int64

## - Data Saving

In [31]:
# Emiision Data
df_combined.to_csv("Cleaned_Combined_Emissions_Yearly.csv", index=False)

In [27]:
# Emission Data
df_agg.to_csv("Cleaned_Emissions_Yearly.csv", index=False)

In [28]:
# GDP Data
df_yearly.to_csv("Cleaned_GDP_Yearly.csv", index=False)